name: Auto AI/ML Blog

on:
  schedule:
    - cron: "0 6 * * *" # run every day at 6 AM UTC
  workflow_dispatch: # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-generativeai

      - name: Run script
        run: python generate_blog.py
        env:
          NEWSDATA_API_KEY: ${{ secrets.NEWSDATA_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit and Push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add content/blogs/
          git commit -m "Add new AI/ML blog post" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
